version: '3'

tasks:
  demo:
    desc: "🚀 Run the complete LocalStack CI/CD workshop demo"
    cmds:
      - bash run.sh

  default:
    desc: "🚀 Default task - run the demo"
    cmds:
      - task: demo